---
driver:
  name: "docker"

platforms:
  - name: "ubuntu"
    command: "sleep infinity"
    image: "docker.io/geerlingguy/docker-ubuntu2204-ansible:latest"
    pre_build_image: true
  - name: "fedora"
    command: "sleep infinity"
    image: "docker.io/geerlingguy/docker-fedora40-ansible:latest"
    pre_build_image: true

scenario:
  name: "install_app"
