---
driver:
  name: 'docker'

platforms:
  - name: 'desktop-layout-ubuntu2204'
    command: 'sleep infinity'
    image: 'docker.io/geerlingguy/docker-ubuntu2204-ansible:latest'
    pre_build_image: true
  - name: 'desktop-layout-ubuntu2404'
    command: 'sleep infinity'
    image: 'docker.io/geerlingguy/docker-ubuntu2404-ansible:latest'
    pre_build_image: true
  - name: 'desktop-layout-ubuntu2604'
    command: 'sleep infinity'
    image: 'docker.io/geerlingguy/docker-ubuntu2604-ansible:latest'
    pre_build_image: true
  - name: 'desktop-layout-missing-schemas'
    command: 'sleep infinity'
    image: 'docker.io/geerlingguy/docker-ubuntu2204-ansible:latest'
    pre_build_image: true

scenario:
  name: 'desktop_layout'
