---
galaxy_info:
  author: 'Jay Thomason'
  description: 'Configure Ubuntu GNOME dock layout policy'
  license: 'MIT'
  min_ansible_version: '2.18'
  platforms:
    - name: 'Ubuntu'
      versions:
        - 'jammy'
        - 'noble'
        - 'resolute'
collections:
  - 'community.general'
dependencies: []
