---
- name: Enable GDM automatic login
  community.general.ini_file:
    path: '{{ auto_login_gdm_config_path }}'
    section: 'daemon'
    option: 'AutomaticLoginEnable'
    value: 'true'
    mode: '0644'
    no_extra_spaces: false
    state: present
  become: true
  when: auto_login_gdm_user | length > 0

- name: Set GDM automatic login user
  community.general.ini_file:
    path: '{{ auto_login_gdm_config_path }}'
    section: 'daemon'
    option: 'AutomaticLogin'
    value: '{{ auto_login_gdm_user }}'
    mode: '0644'
    no_extra_spaces: false
    state: present
  become: true
  when: auto_login_gdm_user | length > 0

- name: Disable GDM automatic login
  community.general.ini_file:
    path: '{{ auto_login_gdm_config_path }}'
    section: 'daemon'
    option: 'AutomaticLoginEnable'
    value: 'false'
    mode: '0644'
    no_extra_spaces: false
    state: present
  become: true
  when: auto_login_gdm_user | length == 0

- name: Remove GDM automatic login user
  community.general.ini_file:
    path: '{{ auto_login_gdm_config_path }}'
    section: 'daemon'
    option: 'AutomaticLogin'
    mode: '0644'
    no_extra_spaces: false
    state: absent
  become: true
  when: auto_login_gdm_user | length == 0

- name: Disable Wayland for GDM
  community.general.ini_file:
    path: '{{ auto_login_gdm_config_path }}'
    section: 'daemon'
    option: 'WaylandEnable'
    value: 'false'
    mode: '0644'
    no_extra_spaces: false
    state: present
  become: true
  when: auto_login_gdm_user | length > 0
