---
- name: Check if GDM configuration is present
  ansible.builtin.stat:
    path: '/etc/gdm3/custom.conf'
  register: auto_login_gdm_config

- name: Configure GDM automatic login
  ansible.builtin.include_tasks: 'gdm.yml'
  when: auto_login_gdm_config.stat.exists

- name: Check if LightDM configuration directory is present
  ansible.builtin.stat:
    path: '/etc/lightdm/lightdm.conf.d'
  register: auto_login_lightdm_config

- name: Configure LightDM automatic login
  ansible.builtin.include_tasks: 'lightdm.yml'
  when: auto_login_lightdm_config.stat.exists
