---
- name: Load distribution variables
  ansible.builtin.include_vars: >-
    {{ lookup('ansible.builtin.first_found', auto_login_vars_params) }}
  vars:
    auto_login_vars_params:
      files:
        - '{{ ansible_facts.distribution }}.yml'
        - '{{ ansible_facts.os_family }}.yml'
      paths:
        - 'vars'

- name: Check if GDM configuration is present
  ansible.builtin.stat:
    path: '{{ auto_login_gdm_config_path }}'
  register: auto_login_gdm_config

- name: Configure GDM automatic login
  ansible.builtin.include_tasks: 'gdm.yml'
  when: auto_login_gdm_config.stat.exists

- name: Check if LightDM configuration directory is present
  ansible.builtin.stat:
    path: '/etc/lightdm/lightdm.conf.d'
  register: auto_login_lightdm_config

- name: Configure LightDM automatic login
  ansible.builtin.include_tasks: 'lightdm.yml'
  when: auto_login_lightdm_config.stat.exists
