---
- name: Update Windows user passwords
  ansible.windows.win_user:
    name: '{{ item.name }}'
    password: '{{ item.password }}'
    state: present
    update_password: '{{ item.update_password | default("always") }}'
  loop: '{{ create_user_accounts }}'
  when: create_user_accounts | length > 0
  no_log: true
