---
- name: Load USB module package data
  ansible.builtin.include_vars: >-
    {{ lookup('ansible.builtin.first_found', disable_usb_storage_vars_files) }}
  vars:
    disable_usb_storage_vars_files:
      files:
        - '{{ ansible_facts.distribution }}.yml'
        - '{{ ansible_facts.os_family }}.yml'
        - 'Linux.yml'
      paths:
        - '{{ role_path }}/vars'
  when: disable_usb_storage_enabled | bool

- name: Install USB module management prerequisite
  ansible.builtin.package:
    name: '{{ disable_usb_storage_kmod_package }}'
    state: present
  become: true
  when: disable_usb_storage_enabled | bool

- name: Create modprobe configuration directory
  ansible.builtin.file:
    group: 'root'
    mode: '0755'
    owner: 'root'
    path: '/etc/modprobe.d'
    state: 'directory'
  become: true
  when: disable_usb_storage_enabled | bool

- name: Install USB mass-storage policy
  ansible.builtin.copy:
    src: 'disable-usb-storage.conf'
    dest: '/etc/modprobe.d/disable-usb-storage.conf'
    group: 'root'
    mode: '0644'
    owner: 'root'
  become: true
  when: disable_usb_storage_enabled | bool

- name: Remove USB mass-storage policy when disabled
  ansible.builtin.file:
    path: '/etc/modprobe.d/disable-usb-storage.conf'
    state: 'absent'
  become: true
  when: not (disable_usb_storage_enabled | bool)

- name: Unload USB mass-storage kernel modules
  community.general.modprobe:
    name: '{{ item }}'
    state: 'absent'
  loop:
    - 'uas'
    - 'usb_storage'
  become: true
  when: disable_usb_storage_enabled | bool
