---
galaxy_info:
  author: 'Jay Thomason'
  description: >-
    Configure desktop display-manager autologin and environment entries
  license: 'MIT'
  min_ansible_version: '2.18'
  platforms:
    - name: 'Debian'
      versions:
        - 'all'
    - name: 'Ubuntu'
      versions:
        - 'all'
dependencies: []
