---
galaxy_info:
  author: 'Jay Thomason'
  description: >-
    Configure detected Linux desktop display-manager and environment policy
  license: 'MIT'
  min_ansible_version: '2.18'
  platforms:
    - name: 'GenericLinux'
      versions:
        - 'all'
dependencies: []
