---
- name: Update all packages with DNF (Fedora/RHEL)  # noqa package-latest
  ansible.builtin.dnf:
    name: "*"
    state: latest
  when: ansible_pkg_mgr in ['dnf', 'dnf5']

- name: Update all packages with APT (Ubuntu/Debian)  # noqa package-latest
  ansible.builtin.apt:
    upgrade: "yes"
    update_cache: true
  when: ansible_pkg_mgr == 'apt'
