---
ssh_client_compression: 'no'
ssh_client_connect_timeout: 0
ssh_client_forward_agent: 'no'
ssh_client_forward_x11: 'no'
ssh_client_host_overrides: []
ssh_client_password_authentication: 'yes'
ssh_client_port: 22
ssh_client_pubkey_authentication: 'yes'
ssh_client_server_alive_count_max: 3
ssh_client_server_alive_interval: 0
ssh_client_strict_host_key_checking: 'ask'
ssh_enabled: true
ssh_server_allow_agent_forwarding: 'yes'
ssh_server_allow_groups: ~
ssh_server_allow_tcp_forwarding: 'yes'
ssh_server_allow_users: ~
ssh_server_client_alive_count_max: 3
ssh_server_client_alive_interval: 0
ssh_server_deny_groups: ~
ssh_server_deny_users: ~
ssh_server_listen_address: '0.0.0.0'
ssh_server_login_grace_time: '1m'
ssh_server_max_auth_tries: 3
ssh_server_password_authentication: 'yes'
ssh_server_permit_empty_passwords: 'no'
ssh_server_permit_root_login: 'no'
ssh_server_port: 22
ssh_server_pubkey_authentication: 'yes'
ssh_server_use_dns: 'no'
ssh_server_x11_forwarding: 'yes'
