---
- name: Install packages with DNF (Fedora/RHEL)
  ansible.builtin.dnf:
    name: "{{ install_apps_packages }}"
    state: present
  when: ansible_pkg_mgr in ['dnf', 'dnf5']

- name: Install packages with APT (Ubuntu/Debian)
  ansible.builtin.apt:
    name: "{{ install_apps_packages }}"
    state: present
    update_cache: true
  when: ansible_pkg_mgr == 'apt'
