---
- name: Check npm executable
  ansible.builtin.command:
    argv:
      - 'npm'
      - '--version'
  changed_when: false
  check_mode: false
  failed_when: false
  register: install_app_npm_version

- name: Validate npm executable
  ansible.builtin.assert:
    that:
      - install_app_npm_version.rc == 0
    fail_msg: >-
      install_app could not run npm after installing its prerequisite.

- name: Install global npm applications
  community.general.npm:
    global: true
    name: '{{ item }}'
    state: present
  loop: '{{ install_app_npm_packages }}'
  become: true
