---
- name: Assert Windows host support
  ansible.builtin.assert:
    that:
      - ansible_facts.os_family == 'Windows'
    fail_msg: 'config_firewall supports Windows hosts only.'

- name: Configure Windows firewall
  ansible.builtin.include_tasks: 'windows/main.yml'
