---
driver:
  name: 'docker'

platforms:
  - name: 'ubuntu-enabled'
    command: 'sleep infinity'
    groups:
      - 'enabled'
    image: 'docker.io/geerlingguy/docker-ubuntu2204-ansible:latest'
    pre_build_image: true
    volumes:
      - '/lib/modules:/lib/modules:ro'
  - name: 'ubuntu-disabled'
    command: 'sleep infinity'
    groups:
      - 'disabled'
    image: 'docker.io/geerlingguy/docker-ubuntu2204-ansible:latest'
    pre_build_image: true
    volumes:
      - '/lib/modules:/lib/modules:ro'
  - name: 'fedora-enabled'
    command: 'sleep infinity'
    groups:
      - 'enabled'
    image: 'docker.io/geerlingguy/docker-fedora44-ansible:latest'
    pre_build_image: true
    volumes:
      - '/lib/modules:/lib/modules:ro'
  - name: 'fedora-disabled'
    command: 'sleep infinity'
    groups:
      - 'disabled'
    image: 'docker.io/geerlingguy/docker-fedora44-ansible:latest'
    pre_build_image: true
    volumes:
      - '/lib/modules:/lib/modules:ro'

scenario:
  name: 'disable_usb_storage'
