---
- name: Install DNF automatic updates plugin
  ansible.builtin.package:
    name: '{{ auto_updates_dnf_package }}'
    state: present
  become: true

- name: Configure dnf-automatic
  ansible.builtin.template:
    src: automatic.conf.j2
    dest: /etc/dnf/automatic.conf
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Ensure DNF automatic timer state
  ansible.builtin.systemd_service:
    name: '{{ auto_updates_dnf_timer }}'
    enabled: '{{ auto_updates_enabled }}'
    state: '{{ "started" if auto_updates_enabled else "stopped" }}'
  become: true
