---
- name: Configure unattended-upgrades for APT systems
  ansible.builtin.include_tasks: 'apt.yml'
  when: ansible_facts.pkg_mgr == 'apt'

- name: Configure automatic updates for DNF systems
  ansible.builtin.include_tasks: 'dnf.yml'
  vars:
    auto_updates_dnf_package: >-
      {{ 'dnf5-plugin-automatic' if ansible_facts.pkg_mgr == 'dnf5'
         else 'dnf-automatic' }}
    auto_updates_dnf_timer: >-
      {{ 'dnf5-automatic.timer' if ansible_facts.pkg_mgr == 'dnf5'
         else 'dnf-automatic.timer' }}
  when: ansible_facts.pkg_mgr in ['dnf', 'dnf5']
