---
- name: Assert supported platform
  ansible.builtin.assert:
    that:
      - ansible_facts.os_family == 'Windows'
    fail_msg: 'allow_ping supports Windows hosts only.'

- name: Manage ping access on Windows hosts
  ansible.builtin.include_tasks: 'windows/main.yml'
