---
- name: Create managed users
  ansible.builtin.user:
    name: "{{ item.name }}"
    comment: "{{ item.comment | default(omit) }}"
    create_home: "{{ item.create_home | default(true) }}"
    groups: "{{ item.groups | join(',') if item.groups is defined else omit }}"
    append: "{{ item.append | default(false) }}"
    password: "{{ item.password }}"
    update_password: always
    shell: "{{ item.shell | default(omit) }}"
  loop: "{{ create_users_users }}"
  when: create_users_users | length > 0

- name: Process SSH keys for each user
  ansible.builtin.include_tasks: 'ssh_keys.yml'
  loop: "{{ create_users_users }}"
  loop_control:
    loop_var: current_user
  when:
    - create_users_users | length > 0
    - current_user.ssh_authorized_keys is defined
