---
driver:
  name: 'docker'

platforms:
  - name: 'fedora'
    image: 'docker.io/geerlingguy/docker-fedora40-ansible:latest'
    pre_build_image: true
    privileged: true
    user: 'root'
    command: '/usr/sbin/init'
    tty: true
    env:
      container: 'docker'
    cgroupns_mode: 'host'
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:rw'

scenario:
  name: 'config_print_services'
