---
galaxy_info:
  author: 'Jay Thomason'
  description: >-
    Disable sleep and hibernate on Windows hosts
  license: 'MIT'
  min_ansible_version: '2.18'
  platforms:
    - name: 'Windows'
      versions:
        - 'all'
collections:
  - 'ansible.windows'
  - 'community.windows'
dependencies: []
