---
- name: Prepare config_ssh scenario
  hosts: all
  gather_facts: false
  tasks:
    - name: Gather minimal facts
      ansible.builtin.setup:
        gather_subset:
          - "!all"
          - "min"

    - name: Remove OpenSSH packages
      ansible.builtin.apt:
        name:
          - 'openssh-client'
          - 'openssh-server'
        state: absent
        update_cache: true

    - name: Create SSHD drop-in directory
      ansible.builtin.file:
        path: '/etc/ssh/sshd_config.d'
        state: directory
        mode: '0755'

    - name: Create SSHD runtime directory
      ansible.builtin.file:
        path: '/run/sshd'
        state: directory
        mode: '0755'

    - name: Seed cloud-init SSHD drop-in
      ansible.builtin.copy:
        dest: '/etc/ssh/sshd_config.d/50-cloud-init.conf'
        content: |
          PasswordAuthentication yes
          PermitRootLogin yes
        mode: '0644'
