---
collections:
  - 'ansible.posix'
  - 'ansible.windows'
  - 'community.windows'

galaxy_info:
  author: 'Jay Thomason'
  description: >-
    Install OpenSSH and own client policy, server policy, firewall access, and
    service state
  license: 'MIT'
  min_ansible_version: '2.18'
  platforms:
    - name: 'Debian'
      versions:
        - 'all'
    - name: 'Ubuntu'
      versions:
        - 'all'
    - name: 'Windows'
      versions:
        - 'all'
dependencies: []
