---
- name: Set power plan
  community.windows.win_power_plan:
    name: '{{ power_policy_plan }}'
  when:
    - power_policy_plan | length > 0

- name: Disable sleep and standby timeouts
  ansible.windows.win_powershell:
    path: 'Disable-PowerPolicySleep.ps1'
  when:
    - power_policy_disable_sleep | bool

- name: Disable hibernate
  ansible.windows.win_command: 'powercfg /hibernate off'
  when:
    - power_policy_disable_hibernate | bool
  changed_when: false
