---
driver:
  name: 'docker'

platforms:
  - name: 'ubuntu'
    command: 'sleep infinity'
    image: 'docker.io/geerlingguy/docker-ubuntu2204-ansible:latest'
    pre_build_image: true

scenario:
  name: 'mount_network_share'
