---
galaxy_info:
  author: 'Jay Thomason'
  description: 'Create managed local users and their authorized SSH keys'
  license: 'MIT'
  min_ansible_version: '2.18'
  platforms:
    - name: 'Debian'
      versions:
        - 'all'
    - name: 'Ubuntu'
      versions:
        - 'all'
dependencies: []
