---
- name: Verify auto_login results
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: Read GDM configuration
      ansible.builtin.slurp:
        src: '/etc/gdm3/custom.conf'
      register: auto_login_gdm_config

    - name: Read LightDM configuration
      ansible.builtin.slurp:
        src: '/etc/lightdm/lightdm.conf.d/autologin.conf'
      register: auto_login_lightdm_config

    - name: Decode automatic login configs
      ansible.builtin.set_fact:
        auto_login_gdm_content: >-
          {{ auto_login_gdm_config.content | b64decode }}
        auto_login_lightdm_content: >-
          {{ auto_login_lightdm_config.content | b64decode }}

    - name: Assert automatic login configuration results
      ansible.builtin.assert:
        that:
          - "'AutomaticLoginEnable = true' in auto_login_gdm_content"
          - "'AutomaticLogin = molecule' in auto_login_gdm_content"
          - "'WaylandEnable = false' in auto_login_gdm_content"
          - "'[SeatDefaults]' in auto_login_lightdm_content"
          - "'autologin-user=molecule' in auto_login_lightdm_content"
          - "'autologin-user-timeout=5' in auto_login_lightdm_content"
        fail_msg: >-
          auto_login did not render the expected automatic login state.

    - name: Remove automatic login with empty users
      ansible.builtin.include_role:
        name: 'jaythomasonprojects.sys_admin.auto_login'
      vars:
        auto_login_gdm_user: ''
        auto_login_lightdm_user: ''

    - name: Read disabled GDM configuration
      ansible.builtin.slurp:
        src: '/etc/gdm3/custom.conf'
      register: auto_login_disabled_gdm_config

    - name: Read disabled LightDM configuration
      ansible.builtin.slurp:
        src: '/etc/lightdm/lightdm.conf.d/autologin.conf'
      register: auto_login_disabled_lightdm_config

    - name: Decode disabled automatic login configs
      ansible.builtin.set_fact:
        auto_login_disabled_gdm_content: >-
          {{ auto_login_disabled_gdm_config.content | b64decode }}
        auto_login_disabled_lightdm_content: >-
          {{ auto_login_disabled_lightdm_config.content | b64decode }}

    - name: Assert automatic login configuration was removed
      ansible.builtin.assert:
        that:
          - "'AutomaticLoginEnable = false' in auto_login_disabled_gdm_content"
          - "'AutomaticLogin = ' not in auto_login_disabled_gdm_content"
          - "'autologin-user=' not in auto_login_disabled_lightdm_content"
          - >-
           'BEGIN ANSIBLE MANAGED BLOCK auto_login' not in
            auto_login_disabled_lightdm_content
        fail_msg: >-
          auto_login did not remove the expected automatic login configuration.
