---
galaxy_info:
  author: 'Jay Thomason'
  description: 'Configure GDM and LightDM automatic login policy'
  license: 'MIT'
  min_ansible_version: '2.18'
  platforms:
    - name: 'Debian'
      versions:
        - 'all'
    - name: 'Fedora'
      versions:
        - 'all'
    - name: 'Ubuntu'
      versions:
        - 'all'
collections:
  - 'community.general'
dependencies: []
