---
driver:
  name: "docker"

platforms:
  - name: "ubuntu"
    command: "sleep infinity"
    image: "docker.io/geerlingguy/docker-ubuntu2204-ansible:latest"
    pre_build_image: true
    user: "root"
  - name: "fedora"
    image: "docker.io/geerlingguy/docker-fedora44-ansible:latest"
    pre_build_image: true
    user: "root"
    privileged: true
    command: "/usr/sbin/init"
    tty: true
    env:
      container: "docker"
    cgroupns_mode: "host"
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"

provisioner:
  name: "ansible"
  env:
    ANSIBLE_REMOTE_USER: "root"

scenario:
  name: "auto_updates"
