---
- name: Prepare auto_updates scenario
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Gather minimal facts
      ansible.builtin.setup:
        gather_subset:
          - "!all"
          - "min"
