---
galaxy_info:
  author: 'Jay Thomason'
  description: 'Configure ntpsec with a caller-provided upstream NTP server'
  license: 'MIT'
  min_ansible_version: '2.18'
  platforms:
    - name: 'Debian'
      versions:
        - 'all'
    - name: 'Ubuntu'
      versions:
        - 'all'
dependencies: []
