---
- name: Assert supported platform
  ansible.builtin.assert:
    that:
      - ansible_facts.system == 'Linux'
    fail_msg: 'config_desktop supports Linux hosts only.'

- name: Configure desktop on Linux hosts
  ansible.builtin.import_tasks: 'linux/main.yml'
