---
- name: Verify config_systemd_units results
  hosts: all
  gather_facts: false
  tasks:
    - name: Gather printer active states  # noqa: command-instead-of-module
      ansible.builtin.command:
        cmd: 'systemctl is-active {{ item }}'
      loop:
        - 'avahi-daemon.service'
        - 'avahi-daemon.socket'
        - 'cups-browsed.service'
      register: config_systemd_units_active_states
      changed_when: false
      failed_when: false

    - name: Assert printer service active states
      ansible.builtin.assert:
        that:
          - config_systemd_units_active_states.results[0].stdout == 'inactive'
          - config_systemd_units_active_states.results[1].stdout == 'inactive'
          - config_systemd_units_active_states.results[2].stdout == 'inactive'

    - name: Gather printer enablement states  # noqa: command-instead-of-module
      ansible.builtin.command:
        cmd: 'systemctl is-enabled {{ item }}'
      loop:
        - 'avahi-daemon.service'
        - 'avahi-daemon.socket'
        - 'cups-browsed.service'
      register: config_systemd_units_enablement
      changed_when: false
      failed_when: false

    - name: Assert printer service enablement states
      ansible.builtin.assert:
        that:
          - config_systemd_units_enablement.results[0].stdout == 'disabled'
          - config_systemd_units_enablement.results[1].stdout == 'disabled'
          - config_systemd_units_enablement.results[2].stdout == 'disabled'
