---
driver:
  name: 'docker'

platforms:
  - name: 'ubuntu'
    command: 'sleep infinity'
    image: 'docker.io/geerlingguy/docker-ubuntu2204-ansible:latest'
    pre_build_image: true
    user: 'root'

provisioner:
  name: 'ansible'
  env:
    ANSIBLE_REMOTE_USER: 'root'

scenario:
  name: 'git'
