---
- name: Detect Debian SSH service name
  ansible.builtin.stat:
    path: /etc/init.d/ssh
  register: config_ssh_debian_service
  when: config_ssh_service_name is none

- name: Select SSH service name
  ansible.builtin.set_fact:
    config_ssh_service_name: >-
      {{ 'ssh' if config_ssh_debian_service.stat.exists else 'sshd' }}
  when: config_ssh_service_name is none

- name: Delete cloud-init SSH configuration files
  ansible.builtin.include_tasks: delete_cloudinit_conf.yml

- name: Apply SSH configuration
  ansible.builtin.include_tasks: ssh_config.yml

- name: Apply SSHD configuration
  ansible.builtin.include_tasks: sshd_config.yml
