---
- name: Converge stable Windows local account policy
  hosts: all
  gather_facts: true
  roles:
    - role: 'jaythomasonprojects.sys_admin.local_accounts'
      local_accounts_users:
        - groups:
            - 'S-1-5-32-544'
          name: 'sa_molecule_admin'
          ssh_authorized_keys:
            - 'ssh-ed25519 AAAATESTADMINSTABLE sys-admin-test'
        - name: 'sa_molecule_stable'
          ssh_authorized_keys:
            - 'ssh-ed25519 AAAATESTSTABLE sys-admin-test'
