---
- name: Create managed Linux users
  ansible.builtin.user:
    name: '{{ item.name }}'
    append: '{{ item.append | default(false) }}'
    comment: '{{ item.comment | default(omit) }}'
    create_home: '{{ item.create_home | default(true) }}'
    groups: >-
      {{ item.groups | join(',')
         if item.groups is defined else omit }}
    password: '{{ item.password }}'
    shell: '{{ item.shell | default(omit) }}'
    state: present
    update_password: always
  loop: '{{ create_user_accounts }}'
  when: create_user_accounts | length > 0

- name: Add SSH authorized keys for Linux users
  ansible.posix.authorized_key:
    user: '{{ item.0.name }}'
    key: '{{ item.1 }}'
    state: present
  loop: >-
    {{ query(
         'ansible.builtin.subelements',
         create_user_accounts,
         'ssh_authorized_keys',
          {
            'skip_missing': true
          }
        ) }}
  loop_control:
    label: '{{ item.0.name }}'
