---
galaxy_info:
  author: 'Jay Thomason'
  description: 'Set the timezone on Windows hosts'
  license: 'MIT'
  min_ansible_version: '2.18'
  platforms:
    - name: 'Windows'
      versions:
        - 'all'
collections:
  - 'ansible.windows'
dependencies: []
