---
- name: Prepare config_git scenario
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Install git
      ansible.builtin.apt:
        name: git
        update_cache: true

    - name: Gather minimal facts
      ansible.builtin.setup:
        gather_subset:
          - '!all'
          - 'min'
