---
- name: Install Windows updates
  ansible.builtin.include_tasks: win.yml
  when: ansible_facts.os_family == 'Windows'

- name: Configure unattended-upgrades for APT systems
  ansible.builtin.include_tasks: apt.yml
  when:
    - ansible_facts.pkg_mgr is defined
    - ansible_facts.pkg_mgr == 'apt'

- name: Configure dnf-automatic for DNF systems
  ansible.builtin.include_tasks: dnf.yml
  when:
    - ansible_facts.pkg_mgr is defined
    - ansible_facts.pkg_mgr in ['dnf', 'dnf5']
