---
- name: Assert supported platform
  ansible.builtin.assert:
    that:
      - >-
        ansible_facts.os_family == 'Windows' or
        (ansible_facts.system == 'Linux' and
        ansible_facts.pkg_mgr in ['apt', 'dnf', 'dnf5'])
    fail_msg: >-
      auto_updates supports Windows and Linux hosts with apt, dnf, or dnf5
      only.

- name: Configure Linux automatic updates
  ansible.builtin.include_tasks: 'linux/main.yml'
  when: ansible_facts.system == 'Linux'

- name: Install Windows updates
  ansible.builtin.include_tasks: 'windows/main.yml'
  when: ansible_facts.os_family == 'Windows'
