---
- name: Manage administrator authorised keys
  when: local_accounts_windows_administrators | length > 0
  no_log: true
  vars:
    local_accounts_windows_administrators: >-
      {{ local_accounts_users
         | selectattr('groups', 'defined')
         | selectattr('groups', 'contains', 'Administrators')
         | list }}
    local_accounts_windows_administrator_keys: >-
      {{ local_accounts_users
         | selectattr('groups', 'defined')
         | selectattr('groups', 'contains', 'Administrators')
         | map(attribute='ssh_authorized_keys', default=[])
         | flatten
         | list }}
  block:
    - name: Write administrator authorised keys
      ansible.windows.win_copy:
        content: '{{ local_accounts_windows_administrator_keys | join("\n") }}'
        dest: 'C:\ProgramData\ssh\administrators_authorized_keys'

    - name: Set administrator authorised-key ACL
      ansible.windows.win_powershell:
        path: 'Set-AuthorizedKeyAcl.ps1'
        parameters:
          Administrator: true

- name: Create standard-user SSH directories
  ansible.windows.win_file:
    path: 'C:\Users\{{ item.name }}\.ssh'
    state: directory
  loop: '{{ local_accounts_users }}'
  when:
    - item.ssh_authorized_keys is defined
    - item.groups is not defined or 'Administrators' not in item.groups
  no_log: true

- name: Write standard-user authorised keys
  ansible.windows.win_copy:
    content: '{{ item.ssh_authorized_keys | join("\n") }}'
    dest: 'C:\Users\{{ item.name }}\.ssh\authorized_keys'
  loop: '{{ local_accounts_users }}'
  when:
    - item.ssh_authorized_keys is defined
    - item.groups is not defined or 'Administrators' not in item.groups
  no_log: true

- name: Set standard-user SSH ACLs
  ansible.windows.win_powershell:
    path: 'Set-AuthorizedKeyAcl.ps1'
    parameters:
      UserName: '{{ item.name }}'
  loop: '{{ local_accounts_users }}'
  when:
    - item.ssh_authorized_keys is defined
    - item.groups is not defined or 'Administrators' not in item.groups
  no_log: true
