---
- name: Update Windows user passwords
  ansible.windows.win_user:
    name: '{{ item.name }}'
    password: '{{ item.password }}'
    state: present
    update_password: '{{ item.update_password | default("always") }}'
  loop: '{{ local_accounts_users }}'
  when: item.password is defined
  no_log: true
