---
- name: Create managed Linux users
  ansible.builtin.user:
    name: '{{ item.name }}'
    append: '{{ item.append | default(false) }}'
    comment: '{{ item.comment | default(omit) }}'
    create_home: '{{ item.create_home | default(true) }}'
    groups: >-
      {{ item.groups | join(',')
         if item.groups is defined else omit }}
    password: '{{ item.password }}'
    shell: '{{ item.shell | default(omit) }}'
    state: present
    update_password: always
  loop: '{{ create_user_accounts }}'
  when: create_user_accounts | length > 0
  become: true
