---
- name: Configure print services on Linux hosts
  when: ansible_facts.os_family != 'Windows'
  block:
    - name: Stop configured printer discovery services
      ansible.builtin.service:
        name: '{{ item.name }}'
        state: '{{ item.state }}'
      loop: '{{ config_print_services_discovery_services }}'
      when: >-
        config_print_services_discovery_services | length > 0

    - name: Disable configured printer discovery services on systemd hosts
      ansible.builtin.systemd:
        name: '{{ item.name }}'
        enabled: '{{ item.enabled }}'
      loop: '{{ config_print_services_discovery_services }}'
      when:
        - ansible_facts.service_mgr | default('') == 'systemd'
        - item.enabled is defined
